#ifndef CONSOLE_INCLUDED
#define CONSOLE_INCLUDED

#include <foundation.h>
#include <input.h>

// console I/O support

void printLine(const char_t* str);
void print(const char_t* format, ...);
void printArgs(const char_t* format, va_list args);

// ForegroundColor

enum ForegroundColor
{
#ifdef GUI_MODE
    FOREGROUND_COLOR_DEFAULT = 0,
    FOREGROUND_COLOR_BLACK = 0,
    FOREGROUND_COLOR_RED = 1,
    FOREGROUND_COLOR_GREEN = 2,
    FOREGROUND_COLOR_YELLOW = 3,
    FOREGROUND_COLOR_BLUE = 4,
    FOREGROUND_COLOR_MAGENTA = 5,
    FOREGROUND_COLOR_CYAN = 6,
    FOREGROUND_COLOR_WHITE = 7,
    FOREGROUND_COLOR_BRIGHT_BLACK = 8,
    FOREGROUND_COLOR_BRIGHT_RED = 9,
    FOREGROUND_COLOR_BRIGHT_GREEN = 10,
    FOREGROUND_COLOR_BRIGHT_YELLOW = 11,
    FOREGROUND_COLOR_BRIGHT_BLUE = 12,
    FOREGROUND_COLOR_BRIGHT_MAGENTA = 13,
    FOREGROUND_COLOR_BRIGHT_CYAN = 14,
    FOREGROUND_COLOR_BRIGHT_WHITE = 15
#else

#ifdef PLATFORM_WINDOWS
    FOREGROUND_COLOR_DEFAULT = 0,
    FOREGROUND_COLOR_BLACK = 0,
    FOREGROUND_COLOR_RED = FOREGROUND_RED,
    FOREGROUND_COLOR_GREEN = FOREGROUND_GREEN,
    FOREGROUND_COLOR_YELLOW = FOREGROUND_GREEN | FOREGROUND_RED,
    FOREGROUND_COLOR_BLUE = FOREGROUND_BLUE,
    FOREGROUND_COLOR_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE,
    FOREGROUND_COLOR_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE,
    FOREGROUND_COLOR_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
    FOREGROUND_COLOR_BRIGHT_BLACK = FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_RED = FOREGROUND_RED | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_GREEN = FOREGROUND_GREEN | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_YELLOW = FOREGROUND_GREEN | FOREGROUND_RED | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_BLUE = FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_MAGENTA = FOREGROUND_RED | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_CYAN = FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY,
    FOREGROUND_COLOR_BRIGHT_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE | FOREGROUND_INTENSITY
#else
    FOREGROUND_COLOR_DEFAULT = 49,
    FOREGROUND_COLOR_BLACK = 30,
    FOREGROUND_COLOR_RED = 31,
    FOREGROUND_COLOR_GREEN = 32,
    FOREGROUND_COLOR_YELLOW = 33,
    FOREGROUND_COLOR_BLUE = 34,
    FOREGROUND_COLOR_MAGENTA = 35,
    FOREGROUND_COLOR_CYAN = 36,
    FOREGROUND_COLOR_WHITE = 37,
    FOREGROUND_COLOR_BRIGHT_BLACK = 90,
    FOREGROUND_COLOR_BRIGHT_RED = 91,
    FOREGROUND_COLOR_BRIGHT_GREEN = 92,
    FOREGROUND_COLOR_BRIGHT_YELLOW = 93,
    FOREGROUND_COLOR_BRIGHT_BLUE = 94,
    FOREGROUND_COLOR_BRIGHT_MAGENTA = 95,
    FOREGROUND_COLOR_BRIGHT_CYAN = 96,
    FOREGROUND_COLOR_BRIGHT_WHITE = 97
#endif

#endif
};

// BackgroundColor

enum BackgroundColor
{
#ifdef GUI_MODE
    BACKGROUND_COLOR_DEFAULT = 15,
    BACKGROUND_COLOR_BLACK = 0,
    BACKGROUND_COLOR_RED = 1,
    BACKGROUND_COLOR_GREEN = 2,
    BACKGROUND_COLOR_YELLOW = 3,
    BACKGROUND_COLOR_BLUE = 4,
    BACKGROUND_COLOR_MAGENTA = 5,
    BACKGROUND_COLOR_CYAN = 6,
    BACKGROUND_COLOR_WHITE = 7,
    BACKGROUND_COLOR_BRIGHT_BLACK = 8,
    BACKGROUND_COLOR_BRIGHT_RED = 9,
    BACKGROUND_COLOR_BRIGHT_GREEN = 10,
    BACKGROUND_COLOR_BRIGHT_YELLOW = 11,
    BACKGROUND_COLOR_BRIGHT_BLUE = 12,
    BACKGROUND_COLOR_BRIGHT_MAGENTA = 13,
    BACKGROUND_COLOR_BRIGHT_CYAN = 14,
    BACKGROUND_COLOR_BRIGHT_WHITE = 15
#else

#ifdef PLATFORM_WINDOWS
    BACKGROUND_COLOR_DEFAULT = 0,
    BACKGROUND_COLOR_BLACK = 0,
    BACKGROUND_COLOR_RED = BACKGROUND_RED,
    BACKGROUND_COLOR_GREEN = BACKGROUND_GREEN,
    BACKGROUND_COLOR_YELLOW = BACKGROUND_GREEN | BACKGROUND_RED,
    BACKGROUND_COLOR_BLUE = BACKGROUND_BLUE,
    BACKGROUND_COLOR_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE,
    BACKGROUND_COLOR_CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE,
    BACKGROUND_COLOR_WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
    BACKGROUND_COLOR_BRIGHT_BLACK = BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_RED = BACKGROUND_RED | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_GREEN = BACKGROUND_GREEN | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_YELLOW = BACKGROUND_GREEN | BACKGROUND_RED | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_BLUE = BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_MAGENTA = BACKGROUND_RED | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_CYAN = BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY,
    BACKGROUND_COLOR_BRIGHT_WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE | BACKGROUND_INTENSITY
#else
    BACKGROUND_COLOR_DEFAULT = 49,
    BACKGROUND_COLOR_BLACK = 40,
    BACKGROUND_COLOR_RED = 41,
    BACKGROUND_COLOR_GREEN = 42,
    BACKGROUND_COLOR_YELLOW = 43,
    BACKGROUND_COLOR_BLUE = 44,
    BACKGROUND_COLOR_MAGENTA = 45,
    BACKGROUND_COLOR_CYAN = 46,
    BACKGROUND_COLOR_WHITE = 47,
    BACKGROUND_COLOR_BRIGHT_BLACK = 100,
    BACKGROUND_COLOR_BRIGHT_RED = 101,
    BACKGROUND_COLOR_BRIGHT_GREEN = 102,
    BACKGROUND_COLOR_BRIGHT_YELLOW = 103,
    BACKGROUND_COLOR_BRIGHT_BLUE = 104,
    BACKGROUND_COLOR_BRIGHT_MAGENTA = 105,
    BACKGROUND_COLOR_BRIGHT_CYAN = 106,
    BACKGROUND_COLOR_BRIGHT_WHITE = 107
#endif

#endif
};

// Console

class Console
{
public:
    static bool brightBackground();

    static ForegroundColor defaultForeground()
    {
        return _defaultForeground;
    }

    static BackgroundColor defaultBackground()
    {
        return _defaultBackground;
    }

    static void initialize();
    static void shutdown();

    static void setLineMode(bool lineMode);
    static void setColor(ForegroundColor foreground, BackgroundColor background);

    static void write(const String& str);
    static void write(const char_t* chars, int len = -1);
    static void write(unichar_t ch, int n = 1);

    static void writeLine(const String& str);
    static void writeLine(const char_t* chars, int len = -1);
    static void writeLine(unichar_t ch, int n = 1);
    static void writeLine();

    static void write(int line, int column, const String& str);
    static void write(int line, int column, const char_t* chars, int len = -1);
    static void write(int line, int column, unichar_t ch, int n = 1);

    static void writeFormatted(const char_t* format, ...);
    static void writeFormattedArgs(const char_t* format, va_list args);

    static void writeLineFormatted(const char_t* format, ...);
    static void writeLineFormattedArgs(const char_t* format, va_list args);

    static unichar_t readChar();
    static String readLine();

    static void getSize(int& width, int& height);
    static void clear();

    static void showCursor(bool show);
    static void setCursorPosition(int line, int column);

    static const Array<InputEvent>& readInput();

protected:
    static ForegroundColor _defaultForeground;
    static BackgroundColor _defaultBackground;

#ifdef PLATFORM_WINDOWS
    static Buffer<INPUT_RECORD> _inputRecords;
#else
    static Array<char> _inputChars;
#endif

    static Array<InputEvent> _inputEvents;
};

#endif
