APPLICATION_NAME=ev

FOUNDATION_HEADERS=foundation.h file.h application.h input.h console.h graphics.h
FOUNDATION_SOURCES=foundation.cpp file.cpp application.cpp input.cpp console.cpp graphics.cpp main.cpp

APPLICATION_HEADERS=$(FOUNDATION_HEADERS) editor.h
APPLICATION_SOURCES=$(FOUNDATION_SOURCES) editor.cpp

TRASH=*.exe *.obj *.ilk *.pdb *.gcc *.clang *.sol *.xlc *.o t.* *.log

VCPP_OPTIONS=/nologo /std:c++latest /utf-8 /EHsc /W3 /wd4244 /wd4267 /wd4723 \
	/I. /D_UNICODE /DUNICODE /D_WIN32_WINNT=_WIN32_WINNT_WIN7 \
	/D_CRT_SECURE_NO_WARNINGS /D_CRT_NON_CONFORMING_SWPRINTFS /Fe:$@
VCPP_DEBUG_OPTIONS=/RTCsu /MTd /Zi /DENABLE_ASSERT
VCPP_RELEASE_OPTIONS=/MT /Ox
VCPP_LINKER_OPTIONS=/link user32.lib ole32.lib dwrite.lib d2d1.lib windowscodecs.lib

GCC_OPTIONS=-std=gnu++14 -Wall -o $@ -I. -Wno-unused-variable -Wno-unused-but-set-variable
GCC_DEBUG_OPTIONS=-g -DENABLE_ASSERT
GCC_RELEASE_OPTIONS=-O3
GCC_LINKER_OPTIONS=-lrt -static-libstdc++

CLANG_OPTIONS=-std=gnu++14 -Wall -o $@ -I. -Wno-unused-variable
CLANG_DEBUG_OPTIONS=-g -DENABLE_ASSERT
CLANG_RELEASE_OPTIONS=-O3
CLANG_LINKER_OPTIONS=-lrt

SOL_OPTIONS=-m64 -std=c++11 +w -o $@ -I. -errtags=yes -erroff=arrowrtn2,wvarhidenmem
SOL_DEBUG_OPTIONS=-g -DENABLE_ASSERT
SOL_RELEASE_OPTIONS=-O3
SOL_LINKER_OPTIONS=

XLC_OPTIONS=-q64 -qlanglvl=extended0x -o $@ -I. -qsuppress=1540-0306
XLC_DEBUG_OPTIONS=-g -DENABLE_ASSERT
XLC_RELEASE_OPTIONS=-O3 -qstrict=nans:infinities
XLC_LINKER_OPTIONS=

all: $(APPLICATION_NAME).dbg.vcpp.exe

$(APPLICATION_NAME).dbg.vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	cl $(VCPP_OPTIONS) $(VCPP_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).dbg.gcc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	g++ $(GCC_OPTIONS) $(GCC_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(GCC_LINKER_OPTIONS)

$(APPLICATION_NAME).dbg.clang: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	clang++ $(CLANG_OPTIONS) $(CLANG_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(CLANG_LINKER_OPTIONS)

$(APPLICATION_NAME).dbg.sol: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	CC $(SOL_OPTIONS) $(SOL_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(SOL_LINKER_OPTIONS)

$(APPLICATION_NAME).dbg.xlc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	xlC_r $(XLC_OPTIONS) $(XLC_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(XLC_LINKER_OPTIONS)

$(APPLICATION_NAME).vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	cl $(VCPP_OPTIONS) $(VCPP_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).gcc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	g++ $(GCC_OPTIONS) $(GCC_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(GCC_LINKER_OPTIONS)

$(APPLICATION_NAME).clang: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	clang++ $(CLANG_OPTIONS) $(CLANG_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(CLANG_LINKER_OPTIONS)

$(APPLICATION_NAME).sol: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	CC $(SOL_OPTIONS) $(SOL_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(SOL_LINKER_OPTIONS)

$(APPLICATION_NAME).xlc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES) makefile
	xlC_r $(XLC_OPTIONS) $(XLC_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(XLC_LINKER_OPTIONS)

clean:
	-del $(TRASH)
	-rm $(TRASH)
