APPLICATION_NAME=ev

FOUNDATION_HEADERS=foundation.h file.h application.h input.h console.h graphics.h
FOUNDATION_SOURCES=foundation.cpp file.cpp application.cpp input.cpp console.cpp graphics.cpp main.cpp

TEST_HEADERS=$(FOUNDATION_HEADERS) test.h
TEST_SOURCES=$(FOUNDATION_SOURCES) test.cpp

APPLICATION_HEADERS=$(FOUNDATION_HEADERS) editor.h
APPLICATION_SOURCES=$(FOUNDATION_SOURCES) editor.cpp

TRASH=*.exe *.obj *.ilk *.pdb *.gcc *.clang *.sol *.xlc *.o t.* *.log

VCPP_OPTIONS=/nologo /std:c++latest /utf-8 /EHsc /W3 /wd4244 /wd4267 /wd4723 \
	/I. /D_UNICODE /DUNICODE /D_WIN32_WINNT=_WIN32_WINNT_WIN7 \
	/D_CRT_SECURE_NO_WARNINGS /D_CRT_NON_CONFORMING_SWPRINTFS /Fe:$@
VCPP_DEBUG_OPTIONS=/RTCsu /MTd /Zi /DENABLE_ASSERT
VCPP_RELEASE_OPTIONS=/MT /Ox
VCPP_LINKER_OPTIONS=/link user32.lib ole32.lib dwrite.lib d2d1.lib windowscodecs.lib

GCC_OPTIONS=-std=gnu++14 -Wall -o $@ -I. -Wno-unused-variable -Wno-unused-but-set-variable -lrt -static-libstdc++
GCC_DEBUG_OPTIONS=-g -DENABLE_ASSERT
GCC_RELEASE_OPTIONS=-O3

CLANG_OPTIONS=-std=gnu++14 -Wall -o $@ -I. -Wno-unused-variable -lrt
CLANG_DEBUG_OPTIONS=-g -DENABLE_ASSERT
CLANG_RELEASE_OPTIONS=-O3

SOL_OPTIONS=-m64 -std=c++11 +w -o $@ -I. -errtags=yes -erroff=arrowrtn2,wvarhidenmem
SOL_DEBUG_OPTIONS=-g -DENABLE_ASSERT
SOL_RELEASE_OPTIONS=-O3

XLC_OPTIONS=-q64 -qlanglvl=extended0x -o $@ -I. -qsuppress=1540-0306
XLC_DEBUG_OPTIONS=-g -DENABLE_ASSERT
XLC_RELEASE_OPTIONS=-O3 -qstrict=nans:infinities

all: $(APPLICATION_NAME).gui.dbg.vcpp.exe

$(APPLICATION_NAME).dbg.vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	cl $(VCPP_OPTIONS) $(VCPP_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).gui.dbg.vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	cl /DGUI_MODE $(VCPP_OPTIONS) $(VCPP_DEBUG_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).dbg.gcc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	g++ $(GCC_OPTIONS) $(GCC_DEBUG_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).dbg.clang: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	clang++ $(CLANG_OPTIONS) $(CLANG_DEBUG_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).dbg.sol: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	CC $(SOL_OPTIONS) $(SOL_DEBUG_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).dbg.xlc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	xlC_r $(XLC_OPTIONS) $(XLC_DEBUG_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	cl $(VCPP_OPTIONS) $(VCPP_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).gui.vcpp.exe: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	cl /DGUI_MODE $(VCPP_OPTIONS) $(VCPP_RELEASE_OPTIONS) $(APPLICATION_SOURCES) $(VCPP_LINKER_OPTIONS)

$(APPLICATION_NAME).gcc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	g++ $(GCC_OPTIONS) $(GCC_RELEASE_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).clang: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	clang++ $(CLANG_OPTIONS) $(CLANG_RELEASE_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).sol: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	CC $(SOL_OPTIONS) $(SOL_RELEASE_OPTIONS) $(APPLICATION_SOURCES)

$(APPLICATION_NAME).xlc: $(APPLICATION_HEADERS) $(APPLICATION_SOURCES)
	xlC_r $(XLC_OPTIONS) $(XLC_RELEASE_OPTIONS) $(APPLICATION_SOURCES)

test.dbg.vcpp.exe: $(TEST_HEADERS) $(TEST_SOURCES)
	cl $(VCPP_OPTIONS) $(VCPP_DEBUG_OPTIONS) $(TEST_SOURCES) $(VCPP_LINKER_OPTIONS)

test.dbg.gcc: $(TEST_HEADERS) $(TEST_SOURCES)
	g++ $(GCC_OPTIONS) $(GCC_DEBUG_OPTIONS) $(TEST_SOURCES)

test.dbg.clang: $(TEST_HEADERS) $(TEST_SOURCES)
	clang++ $(CLANG_OPTIONS) $(CLANG_DEBUG_OPTIONS) $(TEST_SOURCES)

test.dbg.sol: $(TEST_HEADERS) $(TEST_SOURCES)
	CC $(SOL_OPTIONS) $(SOL_DEBUG_OPTIONS) $(TEST_SOURCES)

test.dbg.xlc: $(TEST_HEADERS) $(TEST_SOURCES)
	xlC_r $(XLC_OPTIONS) $(XLC_DEBUG_OPTIONS) $(TEST_SOURCES)

test.vcpp.exe: $(TEST_HEADERS) $(TEST_SOURCES)
	cl $(VCPP_OPTIONS) $(VCPP_RELEASE_OPTIONS)  /DENABLE_ASSERT $(TEST_SOURCES) $(VCPP_LINKER_OPTIONS)

test.gcc: $(TEST_HEADERS) $(TEST_SOURCES)
	g++ $(GCC_OPTIONS) $(GCC_RELEASE_OPTIONS) -DENABLE_ASSERT $(TEST_SOURCES)

test.clang: $(TEST_HEADERS) $(TEST_SOURCES)
	clang++ $(CLANG_OPTIONS) $(CLANG_RELEASE_OPTIONS) -DENABLE_ASSERT $(TEST_SOURCES)

test.sol: $(TEST_HEADERS) $(TEST_SOURCES)
	CC $(SOL_OPTIONS) $(SOL_RELEASE_OPTIONS) -DENABLE_ASSERT $(TEST_SOURCES)

test.xlc: $(TEST_HEADERS) $(TEST_SOURCES)
	xlC_r $(XLC_OPTIONS) $(XLC_RELEASE_OPTIONS) -DENABLE_ASSERT $(TEST_SOURCES)

clean:
	-del $(TRASH)
	-rm $(TRASH)

depl.win: $(APPLICATION_NAME).vcpp.exe
	move /y $(APPLICATION_NAME).vcpp.exe $(APPLICATION_NAME).exe
	"C:\Program Files\7-Zip\7z.exe" a $(APPLICATION_NAME)-win.zip $(APPLICATION_NAME).exe
	move /y $(APPLICATION_NAME)-win.zip docs
    move /y $(APPLICATION_NAME).exe C:\Users\alevichev

depl.mac: $(APPLICATION_NAME).clang
	mv $(APPLICATION_NAME).clang $(APPLICATION_NAME)
	tar cJvf $(APPLICATION_NAME)-mac.tar.bz2 $(APPLICATION_NAME)
	mv $(APPLICATION_NAME)-mac.tar.bz2 docs
	sudo mv $(APPLICATION_NAME) /opt/bin

depl.linux: $(APPLICATION_NAME).gcc
	mv $(APPLICATION_NAME).gcc $(APPLICATION_NAME)
	tar acvf $(APPLICATION_NAME)-linux.tar.bz2 $(APPLICATION_NAME)
	mv $(APPLICATION_NAME)-linux.tar.bz2 docs
	mv $(APPLICATION_NAME) ~/bin/Linux

depl.solaris: $(APPLICATION_NAME).sol
	mv $(APPLICATION_NAME).sol $(APPLICATION_NAME)
	tar acvf $(APPLICATION_NAME)-solaris.tar.bz2 $(APPLICATION_NAME)
	mv $(APPLICATION_NAME)-solaris.tar.bz2 docs
	mv $(APPLICATION_NAME) ~/bin/SunOS

depl.aix: $(APPLICATION_NAME).xlc
	mv $(APPLICATION_NAME).xlc $(APPLICATION_NAME)
	tar acvf $(APPLICATION_NAME)-aix.tar.bz2 $(APPLICATION_NAME)
	mv $(APPLICATION_NAME)-aix.tar.bz2 docs
	mv $(APPLICATION_NAME) ~/bin/AIX
